### ISSUE TITLE
CredentialsError

### ISSUE THREAD

**Issue by MoturiPavani3991** [IBM/cos-web-gallery#13]
I am getting an error while uploading the image "Missing credentials in config"

**Comment by loafyloaf** [comment]
be sure you have file named `.bluemix/cos_credentials` in the root of your user directory that contains the information you copied from the cloud console

**Comment by loafyloaf** [comment]
this error indicates a missing or ill formed `cos_credentials` file.  @MoturiPavani3991 please reopen this issue if you are still having problems...
