### ISSUE TITLE
Signed Urls are empty

### ISSUE THREAD

**Issue by kpschlotter** [IBM/cos-web-gallery#14]
When I run the app, the retrieved signed URLs were empty.
With the following fix it now runs!!!
https://stackoverflow.com/questions/52100144/how-do-i-generate-presigned-links-with-the-nodejs-sdk-for-ibm-cloud-object-stora

**Comment by Srinishaa** [comment]
@kpschlotter @loafyloaf  I am having the same issue, it works pretty well when deployed locally but when hosted on a remote server(in my case cloud foundary) what happens is the empty url array is rendered first, then the image urls are being loaded, so my image gallery shows up empty. Can you please let me know what exactly I can do to fix this issue?
